# Generated by Django 5.2 on 2025-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_user_alter_product_category_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
